---
- name: create user
  hosts: all
  tasks:
    - name: create user
      user:
        name: Buji
        password: Nokia@2022
        uid: 2345
        home: /home/ubuntu/Buji
        comment: "A regular user"
        shell:  /bin/bash


...

