---
- name: create users and create files/directory in user home directory
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file/directory in users home directory
      file:
        name: "{{d}}"
        state: "{{e}}"
...
